nethack_server_netiface: '{{ world_facing_interface_name }}'
host_facing_interface_name: '{{ ansible_default_ipv4.interface }}'
world_facing_interface_name: '{{ ansible_interfaces | difference(["lo", host_facing_interface_name]) | first }}'
# nethack_server_netaddr: '{{ hostvars["inventory_hostname"]["ansible_" nethack_server_netiface] }}'
nethack_server_netaddr: '{{ hostvars[inventory_hostname]["ansible_" + nethack_server_netiface].ipv4.address }}'
# host_base_addr: '{{ ansible_default_ipv4.address | regex_replace("(\\d+)\\.(\\d+)\\.(\\d+)\\.\\d+", "\\1\\.\\2\\.\\3\\.1") }}'
host_base_addr: "{{ nethack_server_netaddr | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.\\d+', '\\1.\\2.\\3.1') }}"