- name: setup mactap network interface
  template:
    src: mactap.if.j2
    dest: /etc/network/interfaces.d/mactap.if
  # notify: reload netiface
  register: network_shit

- name: refresh networking
  setup:
    gather_subset:
      - network
  when: network_shit.changed

- name: reload netiface
  become: yes
  shell: 'ifdown {{ nethack_server_netiface }} && ifup {{ nethack_server_netiface }}'
  # notify: refresh networking
  when: network_shit.changed

- name: fix dmf route
  become: yes
  shell: 'ip route del default && ip route add default via {{ host_base_addr }} && echo {{ host_base_addr }} > /tmp/hej'
  when: network_shit.changed
