- name: Install basic build tools
  apt:
    name: 
      - build-essential
      - automake
      - bison
      - flex
      - libncurses5-dev
      - libncursesw5-dev
      - git
      - alsa-utils
    update_cache: yes
    cache_valid_time: 3600

- name: MAXVOLUME
  command: amixer -c 0 set Master playback 100% unmute

- name: Configure MariaDB Installation
  debconf:
    name: mariadb-server
    question: "{{ item }}"
    vtype: password
    value: ""
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  register: configure_install

- name: Install MariaDB
  apt:
    name: 
      - mariadb-server 
      - libmariadb-dev 
      - libmariadbclient-dev 
      - python-pymysql
  when: configure_install is success

- name: Install dgamelaunch bullshit
  apt:
    name: 
      - sqlite3
      - libsqlite3-dev
      - openbsd-inetd
      - telnetd
    update_cache: yes
    cache_valid_time: 3600

- name: Configure inetd to launch dgamelaunch
  lineinfile:
    path: /etc/inetd.conf
    regex: '^telnet stream tcp nowait root\.root /usr/sbin/tcpd /usr/sbin/in\.telnetd -h -L /home/nh/nethack_server/dgamelaunch$'
    line: telnet stream tcp nowait root.root /usr/sbin/tcpd /usr/sbin/in.telnetd -h -L /home/nh/nethack_server/dgamelaunch

- name: Clone dgamelaunch
  become_user: nh
  git:
    repo: https://github.com/pellsson/dgamelaunch.git
    dest: /home/nh/dgamelaunch
    force: yes

- name: Create tournament DB user
  become: yes
  mysql_user:
    name: nh
    password: nh12
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Patch pellsson mysql shit
  replace:
    path: /home/nh/dgamelaunch/configure.ac
    regexp: 'mysqlclient'
    replace: 'mariadbclient'

- name: Patch pellsson dgl conf shit
  replace:
    path: /home/nh/dgamelaunch/examples/dgamelaunch.conf
    regexp: '\$HOME'
    replace: '/home/nh'

- name: Config dgamelaunch
  become_user: nh
  command:
  args:
    chdir: /home/nh/dgamelaunch
    creates: Makefile
    argv:
      - ./autogen.sh 
      - --enable-debugfile 
      - --enable-sqlite 
      - --enable-shmem 
      - --with-config-file=$HOME/nethack_server/etc/dgamelaunch.conf

- name: Build dgamelaunch
  become_user: nh
  make:
    chdir: /home/nh/dgamelaunch
    target: all

- name: Clone nhweb
  become_user: nh
  git:
    repo: https://github.com/pellsson/nhweb.git
    dest: /home/nh/nhweb
    force: yes

- name: Clone halloffame
  become_user: nh
  git:
    repo: https://github.com/pellsson/halloffame.git
    dest: /home/nh/halloffame
    force: yes
