- name: Install basic build tools
  apt:
    name: 
      - build-essential
      - automake
      - bison
      - flex
      - libncurses5-dev
      - libncursesw5-dev
      - git
      - alsa-utils
    update_cache: yes
    cache_valid_time: 3600

- name: MAXVOLUME
  command: amixer -c 0 set Master playback 100% unmute

- name: Configure MariaDB Installation
  debconf:
    name: mariadb-server
    question: "{{ item }}"
    vtype: password
    value: ""
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  register: configure_install

- name: Install MariaDB
  apt:
    name: 
      - mariadb-server 
      - libmariadb-dev 
      - libmariadbclient-dev 
      - python-pymysql
  when: configure_install is success


- name: Create tournament DB user
  become: yes
  mysql_user:
    name: nh
    password: nh12
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock



